// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcztDDlIazlZuSPeNY0OuE914glOBvdM8',
    appId: '1:677414590656:web:96cacff3beece26b0bf525',
    messagingSenderId: '677414590656',
    projectId: 'khip01-jawara-app',
    authDomain: 'khip01-jawara-app.firebaseapp.com',
    storageBucket: 'khip01-jawara-app.firebasestorage.app',
    measurementId: 'G-FGTZSP7ZMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjxgxXJbv-jHlU7U9P0Rz9mb6ETY_r9eY',
    appId: '1:677414590656:android:f6c30559a13f63600bf525',
    messagingSenderId: '677414590656',
    projectId: 'khip01-jawara-app',
    storageBucket: 'khip01-jawara-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF24O5RNzfHnYoQZhLJ8owd46VNtBxhPY',
    appId: '1:677414590656:ios:4ab53b96ad73b4f30bf525',
    messagingSenderId: '677414590656',
    projectId: 'khip01-jawara-app',
    storageBucket: 'khip01-jawara-app.firebasestorage.app',
    iosBundleId: 'com.AFIV.jawara',
  );

}